### ISSUE TITLE
ahk_id must be a number

### ISSUE THREAD

**Issue by gmankab** [phil294/vimium-everywhere#1]
![image](https://user-images.githubusercontent.com/73340745/213625065-1fffcd90-8a76-43a5-a00b-1835214cc2d2.png)

**Comment by phil294** [comment]
Hello,
I cannot reproduce this error. Did you activate assistive technologies as explained in the Readme? What distro / version / desktop environment are you using? e.g. Ubuntu / Gnome 22.04. If you're using Wayland display server, this is not yet supported, sorry, only X11. Wayland is the default since Ubuntu 22.04 but can be toggled, see Readme of ahk_x11 for details

**Comment by phil294** [comment]
ah hold on, I have an idea what the problem can very likely be. Your terminal displays the title of the currently running program (`./vimium-everywhere` at the top) and the ahk binary searches for its own helper window of the same name and expects to find it but it receives the terminal instead, and this messes up everything.

in other words, if I'm not wrong, this is a bug on my part, which I will try to fix soon. In the meantime, you can workaround it by somehow disabling the feature of your terminal to show the currently executing command in the window title.

**Comment by gmankab** [comment]
sorry that I did not reply for a while

i use arch / gnome 43

problem was in wayland, and everything worked when i switched to x11

very sad that wayland is not supported

**Comment by phil294** [comment]
oh so it works after all, great.

Wayland is still a considerable way to go, if you want to follow the progress (or contribute), check https://github.com/phil294/AHK_X11/issues/2

**Comment by joihn** [comment]
First of all, thanks for this tool, I've been searching for this for a while, 

I have the same issue on 2 different machine running ubuntu 20.04 (x11, gnome 3.36.8).
Very curiously, the tools worked once for 30sec, then crashed, and now I can't start it anymore.

![image](https://user-images.githubusercontent.com/11663917/219195722-a7a3ef4b-3f69-4251-a02d-c31691d27991.png)
after clicking "okay"
![image](https://user-images.githubusercontent.com/11663917/219197888-09585d62-a750-4d76-8ac2-38a460794e8b.png)
edit:
running `sleep 5s && ./vimium-everywhere` and quickly switching the focus away from Terminator seems to sometimes solve the issue (unreliable).

**Comment by phil294** [comment]
ok, I see. I guess it is the window title problem then, after all. In this case, in the meantime a *reliable* workaround should be to put the invocation command inside a differently named bash script, e.g. `echo './Downloads/vimium-everywere' > runner.sh && chmod +x runner.sh'` and `./runner.sh`, as then the terminal title will be entirely unrelated. Can you confirm that?

**Comment by joihn** [comment]
I've tried this also, but without success. It seems like it does like to start when the foreground is [terminator](https://dev.to/xeroxism/how-to-install-terminator-a-linux-terminal-emulator-on-steroids-1m3h)

**Comment by patrickomatik** [comment]
Can confirm that I also have this issue, irrespective of Terminal or Terminator window title. Ubuntu 22.04, X11.

**Comment by phil294** [comment]
I might have fixed this error now. For those affected, if interested, please try out new version 0.2.0 https://github.com/phil294/vimium-everywhere/releases

still X11 only for now
