### ISSUE TITLE
How does this compare to keynav?

### ISSUE THREAD

**Issue by ezhang7423** [phil294/vimium-everywhere#2]
https://github.com/jordansissel/keynav

**Comment by phil294** [comment]
keynav moves the cursor based on a selected region. You basically cut the screen repeatedly in half until you've approximated enough where you want to click.

Vimium Everywhere instead uses the accessibility protocol of Linux distributions to figure out the interactive elements within the active window and lets you jump to one of those elements specifically.

I suggest you compare the beginning of this video of keynav https://yewtu.be/watch?v=OkOb2aD-dVg with the demo video of this very repository from the Readme and I think it should be clear how they work.

**Comment by phil294** [comment]
oh and we might support wayland soon while keynav is limited to x11.
