### ISSUE TITLE
Fatal IO error 11 (Resource temporarily unavailable) on X server :1

### ISSUE THREAD

**Issue by joihn** [phil294/vimium-everywhere#4]
thanks for this tool, 
I sometimes have the following error:
```
./vimium-everywhere
Gtk-Message: 18:29:22.014: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:29:22.016: Failed to load module "canberra-gtk-module"
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11> Gdk-Message: 18:29:26.761: AppRun.wrapped: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
```
ubuntu 20.04, vimium 0.2.1

**Comment by phil294** [comment]
Maybe it's the same as this issue: https://github.com/phil294/AHK_X11/issues/44 but who knows. If you need an immediate fix, you could try using version 0.1.0 instead, where those problems *probably* don't occur. I don't know yet when I can fix those.

But in the meantime, can you give me more details: When does the error happen? Triggered by what? After how long of a usage?

I'll probably add debugging flags soon so you can generate more details error reports.

edit: Nvm I made a VM can can reproduce it
